version: "3.0"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: prod-isi-api-server
    container_name: prod-isi-api-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    container_name: dev-isi-nginx
    restart: unless-stopped
    ports:
      - "${PORT:-3002}:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
  redis:
    restart: unless-stopped
    image: "redis:latest"
    container_name: "prod-redis"
    ports:
      - "6379:6379"