services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: androxxe/dev-isi-api-server:latest
    container_name: dev-isi-api-server
    restart: unless-stopped
    env_file:
      - .env
  nginx:
    image: nginx:latest
    container_name: dev-isi-nginx
    restart: unless-stopped
    ports:
      - "${PORT:-3001}:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
  redis:
    restart: unless-stopped
    image: "redis:latest"
    container_name: "dev-redis"
    ports:
      - "6379:6379"